blank_issues_enabled: false
contact_links:
  - name: Gitter community support
    url: https://gitter.im/24pullrequests/24pullrequests
    about: Need any help? Found any bug? Please chat with us via Gitter.