blank_issues_enabled: false
contact_links:
  - name: Community support
    url: https://github.com/24pullrequests/24pullrequests/discussions
    about: Need any help? Found any bug? Please chat with us in GitHub Discussions.
