name: Feature request
description: Suggest an idea for this project
title: '[FEATURE]: '
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Would you like to have a new feature? Please describe.
      description: A clear and concise description of what the feature is
    validations:
      required: true
  - type: textarea
    attributes:
      label: How would this feature be beneficial for the project
      description: A clear and concise description about the importance of the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false